# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/template/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "direct"
    # Allow up to 10 open pull requests for pip dependencies (default: 5)
    open-pull-requests-limit: 10
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    # Disable rebasing for pull requests
    rebase-strategy: "disabled"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"
    versioning-strategy: increase
